version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/eb-prac.war eb-prac.war
artifacts:
  files:
    - eb-prac.war
    - .ebextensions/**/*
eb_codebuild_settings:
  CodeBuildServiceRole: codebuild-eb-prac-service-role
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/standard:4.0
  Timeout: 60
