version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Running tests
      - mvn test
  post_build:
    commands:
      - mvn package
artifacts:
  files:
    - target/ROOT.war
    - .ebextensions/**/*
