version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/eb-prac.war eb-prac.war
artifacts:
  files:
    - eb-prac.war
    - .ebextensions/**/*
